development:
  adapter: postgresql
  encoding: unicode
  database: receta_development
  pool: 5
  username: kellywaters 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: receta_test
  pool: 5
  username: kellywaters
  password: 